apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- ../../sandbox/ingress
patches:
- patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-rochescaf-tls
    - op: replace
      path: /spec/secretName
      value: argocd-rochescaf-tls
    - op: replace
      path: /spec/dnsNames
      value:
        - argocd.roche.scaf.sixfeetup.com
  target:
    kind: Certificate
    name: argocd-sandbox-rochescaf-tls
- patch: |-
    - op: replace
      path: /metadata/name
      value: argocd-rochescaf
    - op: replace
      path: /spec/routes/0/match
      value: Host(`argocd.roche.scaf.sixfeetup.com`)
    - op: replace
      path: /spec/routes/1/match
      value: Host(`argocd.roche.scaf.sixfeetup.com`) && Headers(`Content-Type`, `application/grpc`)
    - op: replace
      path: /spec/tls
      value: argocd-rochescaf-tls
  target:
    kind: IngressRoute
    name: argocd-sandbox-rochescaf
kind: Kustomization
