apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rochescaf-prod

resources:
  - ../sandbox
  - secrets.yaml

patches:
- target:
    kind: SealedSecret
    name: secrets-config
  path: secrets.yaml
- patch: |-
    - op: replace
      path: /spec/issuerRef/name
      value: letsencrypt-prod
    - op: replace
      path: /spec/dnsNames
      value:
        - api.roche.scaf.sixfeetup.com
        - k8s.roche.scaf.sixfeetup.com
  target:
    kind: Certificate
    name: cluster-cert
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`api.roche.scaf.sixfeetup.com`)
  target:
    kind: IngressRoute
    name: backend-ingress
- patch: |-
    - op: replace
      path: /metadata/annotations/cert-manager.io~1cluster-issuer
      value: letsencrypt-prod
    - op: replace
      path: /spec/routes/0/match
      value: Host(`k8s.roche.scaf.sixfeetup.com`)
  target:
    kind: IngressRoute
    name: k8s-ingress
- patch: |-
    - op: replace
      path: /spec/backup/barmanObjectStore/destinationPath
      value: "s3://rochescaf-prod-backups/"
  target:
    kind: Cluster
    name: postgres

- patch: |-
    - op: add
      path: /data/DISTRIBUTION_ID
      value: "CHANGEME"
  target:
    kind: ConfigMap
    name: app-config

configMapGenerator:
  - name: app-config
    behavior: merge
    literals:
     - ENVIRONMENT="production"
     - DJANGO_SETTINGS_MODULE="config.settings.production"
     - DJANGO_CSRF_TRUSTED_ORIGINS="https://roche.scaf.sixfeetup.com"
     - AWS_S3_CUSTOM_DOMAIN="roche.scaf.sixfeetup.com"

images:
  - name: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-sandbox-backend
    newName: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-backend
    newTag: latest

  - name: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-sandbox-frontend
    newName: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-frontend
    newTag: latest
