apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-cert
spec:
  secretName: cluster-cert-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - api.sandbox.roche.scaf.sixfeetup.com
    - k8s.sandbox.roche.scaf.sixfeetup.com
    - nextjs.roche.scaf.sixfeetup.com
