apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rochescaf-sandbox

resources:
- ../base
- certificate.yaml
- ingress-route.yaml
- postgres.cnpg.yaml
- secrets.yaml


patches:
- patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/command
      value: ["daphne"]
    - op: replace
      path: /spec/template/spec/containers/0/args
      value: ["--bind", "0.0.0.0", "--port", "8000", "--ping-interval", "15", "--ping-timeout", "5", "config.asgi:application"]
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: regcred
    - op: add
      path: /spec/template/spec/initContainers/0/env
      value:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: host
    - op: replace
      path: /spec/template/spec/initContainers/0/command
      value: ["sh", "-c", "until pg_isready -h $(POSTGRES_HOST); do echo waiting for postgres; sleep 2; done;"]
    - op: add
      path: /spec/template/spec/initContainers/1/env
      value:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: uri
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: host
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: postgres-app
              key: uri
  target:
    kind: Deployment
    name: backend
- patch: |-
    - op: add
      path: /spec/template/spec/imagePullSecrets
      value:
        - name: regcred
  target:
    kind: Deployment
    name: frontend
- patch: |-
    - op: add
      path: /data/DISTRIBUTION_ID
      value: "E26MKH0VVSAQTX"
  target:
    kind: ConfigMap
    name: app-config

configMapGenerator:
- behavior: merge
  literals:
  - ENVIRONMENT="sandbox"
  - DJANGO_SETTINGS_MODULE="config.settings.production"
  - DJANGO_CSRF_TRUSTED_ORIGINS="https://sandbox.roche.scaf.sixfeetup.com"
  - CORS_ALLOWED_ORIGINS="https://nextjs.roche.scaf.sixfeetup.com,https://sandbox.roche.scaf.sixfeetup.com"
  - CORS_ALLOW_CREDENTIALS=True
  - AWS_S3_CUSTOM_DOMAIN="sandbox.roche.scaf.sixfeetup.com"
  name: app-config


images:
- name: backend
  newName: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-sandbox-backend
  newTag: a09e7e2
- name: frontend
  newName: 381492128493.dkr.ecr.us-east-1.amazonaws.com/rochescaf-sandbox-frontend
  newTag: a09e7e2
