apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./app.configmap.yaml
- ./django.yaml

- ./frontend.yaml
- ./redis.yaml
- ./pod-priority.yaml
- ./pod-disruption-budgets.yaml  